### ISSUE TITLE
demo 页面中图与代码的分隔符不能拖动

### ISSUE THREAD

**Issue by HaveF** [viserjs/viserjs.github.io#91]
[Viser demo](https://viserjs.github.io/demo.html#/viser/components/special-data-and-range-mark)

![image](https://user-images.githubusercontent.com/54462/52038249-90f23980-256c-11e9-8c37-5b906e62c4cc.png)
* 图与代码的分隔符不能拖动(看起来好困难...)
* 代码没有高亮(当然问题不太大)

**Comment by huxiaoyun** [comment]
呀 ~ 来一起搞啊  @kinghoo5201   跟下这个优化问题

**Comment by kinghoo5201** [comment]
> 呀 ~ 来一起搞啊 @kinghoo5201 跟下这个优化问题

ok 明天搞下！
